#Take a person data and print that info(code,name,age,course,city,Status)
code=input("Enter Code")
name=input("Enter Name")
age=int(input("Enter Age"))
course=input("Enter Course")
city=input("Enter City")
isActive=bool(input("Enter Status(True/False)"))
print("Code:"+code)
print("Name:"+name)
print("Age:"+str(age))
print("Age:",age)
print("Course:"+course)
print("City:"+city)
print("Status:"+str(isActive))
print("Status:",isActive)

           
